make_prg_dependencies_img: "containers/make_prg_dependencies.simg"
coverages: 
  - 30
  - 60
  - 100
subsample:
  strategies:
    - filter
#    - random
  container: "containers/subsample.simg"
  mean_q_weight: 10
  min_length: 150
plot: 
  container: "/hps/nobackup2/singularity/mbhall88/nanoplot.v1.26.3.simg"
samples: 
  - CFT073
  - ST38
  - 063_STEC
  - H131800734
pandora_executable: "/nfs/research1/zi/mbhall/Software/pandora/build-release/pandora"
original_prg: "data/prgs/ecoli_pangenome_PRG_210619.fa"
