# input data configs
original_prg: "data_20_way/data_for_pipeline/custom/prgs/ecoli_pangenome_PRG_210619.fa"
sample_data_dir: "data_20_way/data_for_pipeline/samples"
msas_dir: "data_20_way/data_for_pipeline/custom/msas"
msas_csv: "data_20_way/data_for_pipeline/custom/msas/msas.csv"
prgs_dir: "data_20_way/data_for_pipeline/custom/prgs"

# output configs
analysis_output_dir: "analysis_20_way"

# time and memory limits
make_prg_timeout_in_second: 86400 # 1 day
make_prg_memory_limit: 32000
clustalo_timeout_in_second: 86400 # 1 day

# execution config
coverages:
  - 30
  - 60
  - 100

technologies:
  - nanopore
  - illumina

samples:
  - 063_STEC
  - CFT073
  - Escherichia_coli_MINF_1A
  - Escherichia_coli_MINF_1D
  - Escherichia_coli_MINF_7C
  - Escherichia_coli_MINF_8D
  - Escherichia_coli_MINF_9A
  - Escherichia_coli_MSB1_1A
  - Escherichia_coli_MSB1_3B
  - Escherichia_coli_MSB1_4E
  - Escherichia_coli_MSB1_4I
  - Escherichia_coli_MSB1_6C
  - Escherichia_coli_MSB1_7A
  - Escherichia_coli_MSB1_7C
  - Escherichia_coli_MSB1_8B
  - Escherichia_coli_MSB1_8G
  - Escherichia_coli_MSB1_9D
  - Escherichia_coli_MSB2_1A
  - H131800734
  - ST38

subsample:
  strategies:
#    - filter
    - random
  mean_q_weight: 10
  min_length: 150
  seed: 42


container: docker:///leandroishilima/pandora_analysis_pipeline:pandora_paper_tag1
