output_folder: pandora_output_pandora_paper_tag1_4way_new_basecall
original_prg: ../data/prgs/ecoli_pangenome_PRG_210619.fa

coverages:
  - 100

subsamplings:
  - random

technologies:
  - nanopore

samples: metadata/samples_pandora_paper_tag1.4way_new_basecall.csv
subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.4way_new_basecall.csv

msas_dir: ../data/msas
msas_csv: metadata/msas_pandora_paper_tag1.csv

complex_MSA_sequence_threshold: 50

pandora_container: docker://leandroishilima/pandora_analysis_pipeline:pandora_paper_tag1

