output_folder: pandora_output_pandora_paper_tag1

coverages:
  - 100

subsamplings:
  - random

technologies:
  - illumina
  - nanopore

samples: metadata/samples_pandora_paper_tag1.csv
subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.csv
msas_dir: ../data/msas

pandora_URL: "https://github.com/leoisl/pandora/releases/download/0.9.0-rc1_RAM/pandora-linux-precompiled-v0.9.0-rc1_RAM"
make_prg_URL: "https://github.com/leoisl/make_prg/releases/download/v0.2.0_prototype/make_prg_0.2.0_prototype"
containers:
  mafft: docker://leandroishilima/pandora_workflow_mafft:latest
