# data configs
original_prg: "data/prgs/ecoli_pangenome_PRG_210619.fa"
sample_data_dir: "data"
msas_dir: "data/msas"
prgs_dir: "data/prgs"
analysis_output_dir: "analysis"
msas_csv: "data/msas/msas.csv"
make_prg_timeout_in_second: 21600
clustalo_timeout_in_second: 21600
make_prg_memory_limit: 32000

coverages:
  - 30
  - 60
  - 100

technologies:
  - nanopore
  - illumina

samples:
  - CFT073
  - ST38
  - 063_STEC
  - H131800734

subsample:
  strategies:
#    - filter
    - random
  container: "containers/subsample.simg"
  mean_q_weight: 10
  min_length: 150
  seed: 42


# other configs
pandora_executable: "/hps/nobackup/research/zi/projects/pandora_paper/pandora/pandora/build/pandora"
make_prg_dependencies_img: "containers/make_prg_dependencies.simg"
plot:
  container: "/hps/nobackup2/singularity/mbhall88/nanoplot.v1.26.3.simg"


